import Header from '@/components/Header'
import StoreInitializer from '@/components/StoreInitializer'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  
  return (
    <html lang="en">
      <body>
        <StoreInitializer />
        <Header />
        {children}
        </body>
    </html>
  )
}
