import Header from '@/components/Header'
import './globals.css'
import {CartProvider, CartDispatchProvider} from './cart-provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  
  return (
    <html lang="en">
      <body>
        <CartDispatchProvider>
        <CartProvider>
        <Header />
        {children}
        </CartProvider>
        </CartDispatchProvider>
        </body>
    </html>
  )
}
